spring:
  profiles:
    group:
      dev: "common"
---
spring:
  profiles:
    group:
      prod: "common"
---
spring:
  profiles:
    group:
      prod-eureka: "common,eureka"
---
spring:
  profiles:
    active: ${PROFILE:prod-eureka}
